---

- name: ensure nginx is present
  yum: name=nginx state=latest

- name: nginx ssl folder
  file: dest=/etc/nginx/ssl state=directory

- name: ensure nginx conf is in place
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

# we can add proxy config if required as per requirment

- name: set nginx default conf
  copy: src=nginx_default.conf dest=/etc/nginx/conf.d/default.conf
  notify:
    - restart nginx

- name: ensure nginx service starts
  service: name=nginx state=reloaded enabled=yes
  #shell: nginx -s reload 
